---
- name: Remove MySQL Database Container from Worker Node
  hosts: workernodes
  become: yes
  vars:
    db_container_name: mysql-container

  tasks:
    - name: Ensure MySQL Database container is stopped and removed
      community.docker.docker_container:
        name: "{{ db_container_name }}"
        state: absent
